const BASE_URL = import.meta.env.VITE_BASE_URL || import.meta.env.VITE_API_BASE_URL || 'http://localhost:3000/api/v1'

export const ENDPOINTS = {
  AUTH: {
    LOGIN: `${BASE_URL}/auth/login`,
    LOGOUT: `${BASE_URL}/auth/logout`,
    REGISTER: `${BASE_URL}/auth/register`,
    SIGNUP: `${BASE_URL}/auth/signup`,
    REFRESH: `${BASE_URL}/auth/refresh`,
    PROFILE: `${BASE_URL}/users/profile`,
    OTP_VERIFY: `${BASE_URL}/users/otp/verify`,
    FORGOT_PASSWORD: `${BASE_URL}/auth/password`,
    RESET_PASSWORD: `${BASE_URL}/auth/password`,
  },
  USERS: {
    PROFILE: `${BASE_URL}/users/profile`,
    PASSWORD: `${BASE_URL}/users/password`,
    OTP_TOGGLE: `${BASE_URL}/users/otp/toggle`,
    LIST: `${BASE_URL}/users`,
    DETAIL: (id) => `${BASE_URL}/users/${id}`,
    ASSIGN_ROLE: (id, roleId) => `${BASE_URL}/users/${id}/role/${roleId}`,
    ASSIGN_PERMISSIONS: (id) => `${BASE_URL}/users/${id}/permissions`,
    UNASSIGN_PERMISSIONS: (id) => `${BASE_URL}/users/${id}/permissions`,
    BLOCK: (id) => `${BASE_URL}/users/${id}/block`,
    UNBLOCK: (id) => `${BASE_URL}/users/${id}/unblock`,
  },
  ROLES: {
    LIST: `${BASE_URL}/roles`,
    UPDATE: (id) => `${BASE_URL}/roles/${id}`,
  },
  PERMISSIONS: {
    LIST: `${BASE_URL}/permissions`,
  },
  BADGES: {
    LIST: `${BASE_URL}/badges`,
    DETAIL: (id) => `${BASE_URL}/badges/${id}`,
    CREATE: `${BASE_URL}/badges`,
    UPDATE: (id) => `${BASE_URL}/badges/${id}`,
    DELETE: (id) => `${BASE_URL}/badges/${id}`,
    ADD_USER: (id, userId) => `${BASE_URL}/badges/${id}/users/${userId}`,
    REMOVE_USER: (id, userId) => `${BASE_URL}/badges/${id}/users/${userId}`,
  },
  PRODUCTS: {
    LIST: `${BASE_URL}/products/products`,
    DETAIL: (id) => `${BASE_URL}/products/products/${id}`,
    CREATE: `${BASE_URL}/products/products`,
    UPDATE: (id) => `${BASE_URL}/products/products/${id}`,
    DELETE: (id) => `${BASE_URL}/products/products/${id}`,
    REVIEWS: {
      DELETE: (productId, reviewId) => `${BASE_URL}/products/products/${productId}/reviews/${reviewId}`,
    },
    PRODUCT_META: {
      LIST: (productId) => `${BASE_URL}/products/products/${productId}/product_meta`,
      CREATE: (productId) => `${BASE_URL}/products/products/${productId}/product_meta`,
      UPDATE: (productId, metaId) => `${BASE_URL}/products/products/${productId}/product_meta/${metaId}`,
      DELETE: (productId, metaId) => `${BASE_URL}/products/products/${productId}/product_meta/${metaId}`,
    },
    VARIANTS: {
      LIST: (productId) => `${BASE_URL}/products/products/${productId}/variants`,
      DETAIL: (variantId) => `${BASE_URL}/products/variants/${variantId}`,
      CREATE: (productId) => `${BASE_URL}/products/products/${productId}/variants`,
      UPDATE: (variantId) => `${BASE_URL}/products/variants/${variantId}`,
      DELETE: (variantId) => `${BASE_URL}/products/variants/${variantId}`,
      OPTIONS: {
        LIST: (variantId) => `${BASE_URL}/products/variants/${variantId}/options`,
        CREATE: (variantId) => `${BASE_URL}/products/variants/${variantId}/options`,
        UPDATE: (variantId, optionId) => `${BASE_URL}/products/variants/${variantId}/options/${optionId}`,
        DELETE: (variantId, optionId) => `${BASE_URL}/products/variants/${variantId}/options/${optionId}`,
        IMAGES: {
          CREATE: (variantId, optionId) => `${BASE_URL}/products/variants/${variantId}/options/${optionId}/images`,
          DELETE: (variantId, optionId, imageId) => `${BASE_URL}/products/variants/${variantId}/options/${optionId}/images/${imageId}`,
        },
      },
    },
    IMAGES: {
      LIST: `${BASE_URL}/products/images`,
      CREATE: (productId) => `${BASE_URL}/products/products/${productId}/images`,
      UPDATE: (imageId) => `${BASE_URL}/products/images/${imageId}`,
      DELETE: (productId, imageId) => `${BASE_URL}/products/products/${productId}/images/${imageId}`,
    },
  },
  INVENTORY: {
    VARIANT_STOCKS: {
      LIST: `${BASE_URL}/inventory/variant_stocks`,
      DETAIL: (stockId) => `${BASE_URL}/inventory/variant_stocks/${stockId}`,
      CREATE: `${BASE_URL}/inventory/variant_stocks`,
      UPDATE: (stockId) => `${BASE_URL}/inventory/variant_stocks/${stockId}`,
      DELETE: (stockId) => `${BASE_URL}/inventory/variant_stocks/${stockId}`,
    },
    DOWNTIMES: {
      LIST: `${BASE_URL}/inventory/downtimes`,
      DETAIL: (id) => `${BASE_URL}/inventory/downtimes/${id}`,
      CREATE: `${BASE_URL}/inventory/downtimes`,
      UPDATE: (id) => `${BASE_URL}/inventory/downtimes/${id}`,
      DELETE: (id) => `${BASE_URL}/inventory/downtimes/${id}`,
      END_EARLY: (id) => `${BASE_URL}/inventory/downtimes/${id}/end_early`,
    },
  },
  ORDERS: {
    CREATE: `${BASE_URL}/orders`,
    LIST: `${BASE_URL}/orders`,
    DETAIL: (id) => `${BASE_URL}/orders/${id}`,
  },
  CATEGORIES: {
    LIST: `${BASE_URL}/categories`,
    DETAIL: (id) => `${BASE_URL}/categories/${id}`,
    CREATE: `${BASE_URL}/categories`,
    UPDATE: (id) => `${BASE_URL}/categories/${id}`,
    DELETE: (id) => `${BASE_URL}/categories/${id}`,
  },
  SUB_CATEGORIES: {
    LIST: `${BASE_URL}/sub_categories`,
    DETAIL: (id) => `${BASE_URL}/sub_categories/${id}`,
    CREATE: `${BASE_URL}/sub_categories`,
    UPDATE: (id) => `${BASE_URL}/sub_categories/${id}`,
    DELETE: (id) => `${BASE_URL}/sub_categories/${id}`,
  },
  WAREHOUSES: {
    LIST: `${BASE_URL}/warehouses`,
    DETAIL: (id) => `${BASE_URL}/warehouses/${id}`,
    CREATE: `${BASE_URL}/warehouses`,
    UPDATE: (id) => `${BASE_URL}/warehouses/${id}`,
    DELETE: (id) => `${BASE_URL}/warehouses/${id}`,
    IMAGES: {
      LIST: (warehouseId) => `${BASE_URL}/warehouses/${warehouseId}/images`,
      CREATE: (warehouseId) => `${BASE_URL}/warehouses/${warehouseId}/images`,
      DELETE: (warehouseId, imageId) => `${BASE_URL}/warehouses/${warehouseId}/images/${imageId}`,
    },
  },
  DELIVERY: {
    ZONES: {
      LIST: `${BASE_URL}/delivery_zones`,
      CREATE: `${BASE_URL}/delivery_zones`,
      UPDATE: (id) => `${BASE_URL}/delivery_zones/${id}`,
      DELETE: (id) => `${BASE_URL}/delivery_zones/${id}`,
    },
    WEIGHT_TIERS: {
      LIST: `${BASE_URL}/delivery_weight_tiers`,
      CREATE: `${BASE_URL}/delivery_weight_tiers`,
      UPDATE: (id) => `${BASE_URL}/delivery_weight_tiers/${id}`,
      DELETE: (id) => `${BASE_URL}/delivery_weight_tiers/${id}`,
    },
    HIGH_VALUE_RATES: {
      LIST: `${BASE_URL}/delivery_high_value_rates`,
      CREATE: `${BASE_URL}/delivery_high_value_rates`,
      UPDATE: (id) => `${BASE_URL}/delivery_high_value_rates/${id}`,
      DELETE: (id) => `${BASE_URL}/delivery_high_value_rates/${id}`,
    },
    SETTINGS: `${BASE_URL}/delivery_settings`,
  },
  AFFILIATES: {
    LIST: `${BASE_URL}/affiliates`,
    DETAIL: (id) => `${BASE_URL}/affiliates/${id}`,
    APPROVE: (id) => `${BASE_URL}/affiliates/${id}/approve`,
    REJECT: (id) => `${BASE_URL}/affiliates/${id}/reject`,
    SUSPEND: (id) => `${BASE_URL}/affiliates/${id}/suspend`,
    REACTIVATE: (id) => `${BASE_URL}/affiliates/${id}/reactivate`,
  },
  CONTACTS: {
    LIST: `${BASE_URL}/contacts`,
    DELETE: (id) => `${BASE_URL}/contacts/${id}`,
  },
  SUPPORT: {
    LIST: `${BASE_URL}/support_requests`,
    DETAIL: (id) => `${BASE_URL}/support_requests/${id}`,
    UPDATE: (id) => `${BASE_URL}/support_requests/${id}`,
    DELETE: (id) => `${BASE_URL}/support_requests/${id}`,
  },
}

export { BASE_URL }
